// Writes the self-hosted fonts into public/fonts.
//
// 1. The CJK subsets embedded in the legacy board (demo/index.html, generated by
//    tools/embed_fonts.py) are decoded from base64 as-is.
// 2. The Latin faces used by the EN text come from the @fontsource packages
//    (EB Garamond, Inter, JetBrains Mono; all SIL OFL 1.1).
//
// Usage: node tools/fonts.mjs
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'public', 'fonts');
mkdirSync(out, { recursive: true });

const FILES = {
  'Elysium Serif SC/400': 'serif-sc-400.woff2',
  'Elysium Serif SC/600': 'serif-sc-600.woff2',
  'Elysium Sans SC/600': 'sans-sc-600.woff2',
  'Elysium Mono SC/400': 'mono-sc-400.woff2',
  'Elysium Mono/400': 'mono-400.woff2',
};

const html = readFileSync(join(root, 'demo', 'index.html'), 'utf8');
const re = /@font-face\{font-family:"([^"]+)";font-style:normal;font-weight:(\d+);[^}]*?base64,([A-Za-z0-9+/=]+)\)/g;
let n = 0;
for (const m of html.matchAll(re)) {
  const name = FILES[`${m[1]}/${m[2]}`];
  if (!name) throw new Error(`unexpected face ${m[1]} ${m[2]}`);
  const buf = Buffer.from(m[3], 'base64');
  writeFileSync(join(out, name), buf);
  console.log(`${name.padEnd(28)} ${String(buf.length).padStart(7)} B  (${m[1]} ${m[2]})`);
  n++;
}
if (n !== Object.keys(FILES).length) throw new Error(`expected ${Object.keys(FILES).length} faces, found ${n}`);

const LATIN = [
  ['@fontsource/eb-garamond/files/eb-garamond-latin-400-normal.woff2', 'eb-garamond-400.woff2'],
  ['@fontsource/eb-garamond/files/eb-garamond-latin-600-normal.woff2', 'eb-garamond-600.woff2'],
  ['@fontsource/inter/files/inter-latin-600-normal.woff2', 'inter-600.woff2'],
  ['@fontsource/jetbrains-mono/files/jetbrains-mono-latin-400-normal.woff2', 'jetbrains-mono-400.woff2'],
];
for (const [src, name] of LATIN) {
  copyFileSync(join(root, 'node_modules', src), join(out, name));
  console.log(`${name.padEnd(28)} (latin, ${src.split('/')[1]})`);
}
